name: app_kardex
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_login: ^5.0.0
  font_awesome_flutter: ^10.7.0
  youtube_player_flutter: ^9.1.1
  pdf: ^3.10.8  # Para generar el PDF
  path_provider: ^2.1.1  # Para encontrar el directorio donde guardar el PDF
  open_file: ^3.3.2  # Para abrir el PDF después de generarlo (opcional)
  url_launcher: ^6.1.0

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/